package joyin.takgi.paysage.esim

object EsimSgp22SampleCollectionTemplateBuilder {
    fun build(commandContext: EsimSgp22SampleContext): String = buildString {
        appendLine("Paysage SGP.22 安全样本采集模板")
        appendLine("隐私边界: 不外发原始 APDU、TLV value、EID、ICCID、IMSI、手机号、运营商二维码或激活码。")
        appendLine()
        appendLine("1. 命令上下文")
        appendLine("- 选择上下文: ${commandContext.label}")
        appendLine("- 实际 ES10x/诊断命令名: <填写命令名或保持未知>")
        appendLine("- 通道: <USB CCID / OMAPI / 系统公开 API / 其它>")
        appendLine("- 目标: <ISD-R / profile 只读 / notification 只读 / 通用只读>")
        appendLine()
        appendLine("2. 设备与环境")
        appendLine("- Android 版本/厂商 ROM: <可泛化填写，不写序列号>")
        appendLine("- eSIM 状态: <支持/不支持/系统 LPA 缺失/需要授权>")
        appendLine("- Reader: <USB CCID 型号或 OMAPI reader 名称，可脱敏>")
        appendLine()
        appendLine("3. 本地分析步骤")
        appendLine("- 将 APDU 响应原文只粘贴到 Paysage 当前页面。")
        appendLine("- 选择正确命令上下文后点击脱敏分析。")
        appendLine("- 检查隐私审计摘要，确认敏感/可能敏感节点未展示 value。")
        appendLine("- 只复制 Paysage 生成的脱敏分析片段用于协作。")
        appendLine()
        appendLine("4. 可外发内容")
        appendLine("- 脱敏分析片段: <粘贴 Paysage 复制的脱敏片段>")
        appendLine("- 复现步骤: <描述点击顺序，不包含原始 APDU>")
        appendLine("- 期望结果: <例如 profile 列表结构可识别 / notification 候选可识别>")
        appendLine("- 实际结果: <例如解析异常 / 低置信候选 / 状态字 6Cxx>")
        appendLine()
        appendLine("5. 外发前检查")
        appendLine("- [ ] 未包含原始 APDU 响应全文")
        appendLine("- [ ] 未包含 TLV value")
        appendLine("- [ ] 未包含 EID/ICCID/IMSI/手机号/IMEI")
        appendLine("- [ ] 未包含运营商二维码、激活码或确认码")
        appendLine("- [ ] 已包含命令上下文和 Paysage 脱敏分析片段")
    }.trimEnd()
}
