package takagi.ru.saison.ui.theme

import androidx.compose.ui.graphics.Color

// Default Material Design 3 Colors
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

// Sakura Theme (Cherry Blossom)
// Light Mode
val SakuraPrimary = Color(0xFFE91E63)
val SakuraOnPrimary = Color(0xFFFFFFFF)
val SakuraPrimaryContainer = Color(0xFFFCE4EC)
val SakuraOnPrimaryContainer = Color(0xFF880E4F)
val SakuraSecondary = Color(0xFFFF4081)
val SakuraOnSecondary = Color(0xFFFFFFFF)
val SakuraSecondaryContainer = Color(0xFFFFCDD2)
val SakuraOnSecondaryContainer = Color(0xFFC2185B)
val SakuraTertiary = Color(0xFFF06292)
val SakuraOnTertiary = Color(0xFFFFFFFF)
val SakuraTertiaryContainer = Color(0xFFFFF0F3)
val SakuraOnTertiaryContainer = Color(0xFFAD1457)
val SakuraError = Color(0xFFB00020)
val SakuraOnError = Color(0xFFFFFFFF)
val SakuraErrorContainer = Color(0xFFFDEDED)
val SakuraOnErrorContainer = Color(0xFF8C0009)
val SakuraBackground = Color(0xFFFFF5F8)  // 带粉色调的背景
val SakuraOnBackground = Color(0xFF1C1B1F)
val SakuraSurface = Color(0xFFFFF8FA)  // 带粉色调的表面
val SakuraOnSurface = Color(0xFF1C1B1F)
val SakuraSurfaceVariant = Color(0xFFF3E0E6)
val SakuraOnSurfaceVariant = Color(0xFF4A4458)
val SakuraOutline = Color(0xFF7A757F)
val SakuraOutlineVariant = Color(0xFFCAC4D0)

// Dark Mode
val SakuraDarkPrimary = Color(0xFFF48FB1)
val SakuraDarkOnPrimary = Color(0xFF880E4F)
val SakuraDarkPrimaryContainer = Color(0xFFC2185B)
val SakuraDarkOnPrimaryContainer = Color(0xFFFCE4EC)
val SakuraDarkSecondary = Color(0xFFFF80AB)
val SakuraDarkOnSecondary = Color(0xFF880E4F)
val SakuraDarkSecondaryContainer = Color(0xFFC2185B)
val SakuraDarkOnSecondaryContainer = Color(0xFFFFCDD2)
val SakuraDarkTertiary = Color(0xFFF48FB1)
val SakuraDarkOnTertiary = Color(0xFF880E4F)
val SakuraDarkTertiaryContainer = Color(0xFFAD1457)
val SakuraDarkOnTertiaryContainer = Color(0xFFFFF0F3)
val SakuraDarkError = Color(0xFFCF6679)
val SakuraDarkOnError = Color(0xFF000000)
val SakuraDarkErrorContainer = Color(0xFFB00020)
val SakuraDarkOnErrorContainer = Color(0xFFFDEDED)
val SakuraDarkBackground = Color(0xFF1F1719)  // 带粉色调的深色背景
val SakuraDarkOnBackground = Color(0xFFE6E1E5)
val SakuraDarkSurface = Color(0xFF231A1D)  // 带粉色调的深色表面
val SakuraDarkOnSurface = Color(0xFFE6E1E5)
val SakuraDarkSurfaceVariant = Color(0xFF4A3E42)  // 带粉色调
val SakuraDarkOnSurfaceVariant = Color(0xFFCAC4D0)
val SakuraDarkOutline = Color(0xFF938F99)
val SakuraDarkOutlineVariant = Color(0xFF49454F)

// Mint Theme
// Light Mode
val MintPrimary = Color(0xFF00BFA5)
val MintOnPrimary = Color(0xFFFFFFFF)
val MintPrimaryContainer = Color(0xFFB2DFDB)
val MintOnPrimaryContainer = Color(0xFF004D40)
val MintSecondary = Color(0xFF64FFDA)
val MintOnSecondary = Color(0xFF004D40)
val MintSecondaryContainer = Color(0xFFE0F2F1)
val MintOnSecondaryContainer = Color(0xFF00695C)
val MintTertiary = Color(0xFF1DE9B6)
val MintOnTertiary = Color(0xFF000000)
val MintTertiaryContainer = Color(0xFFC8E6C9)
val MintOnTertiaryContainer = Color(0xFF00695C)
val MintError = Color(0xFFB00020)
val MintOnError = Color(0xFFFFFFFF)
val MintErrorContainer = Color(0xFFFDEDED)
val MintOnErrorContainer = Color(0xFF8C0009)
val MintBackground = Color(0xFFF5FFFD)  // 带薄荷绿色调的背景
val MintOnBackground = Color(0xFF1C1B1F)
val MintSurface = Color(0xFFF8FFFE)  // 带薄荷绿色调的表面
val MintOnSurface = Color(0xFF1C1B1F)
val MintSurfaceVariant = Color(0xFFE0F2F1)
val MintOnSurfaceVariant = Color(0xFF424242)
val MintOutline = Color(0xFF757575)
val MintOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val MintDarkPrimary = Color(0xFF64FFDA)
val MintDarkOnPrimary = Color(0xFF004D40)
val MintDarkPrimaryContainer = Color(0xFF00897B)
val MintDarkOnPrimaryContainer = Color(0xFFB2DFDB)
val MintDarkSecondary = Color(0xFF64FFDA)
val MintDarkOnSecondary = Color(0xFF004D40)
val MintDarkSecondaryContainer = Color(0xFF00695C)
val MintDarkOnSecondaryContainer = Color(0xFFE0F2F1)
val MintDarkTertiary = Color(0xFF69F0AE)
val MintDarkOnTertiary = Color(0xFF004D40)
val MintDarkTertiaryContainer = Color(0xFF00695C)
val MintDarkOnTertiaryContainer = Color(0xFFC8E6C9)
val MintDarkError = Color(0xFFCF6679)
val MintDarkOnError = Color(0xFF000000)
val MintDarkErrorContainer = Color(0xFFB00020)
val MintDarkOnErrorContainer = Color(0xFFFDEDED)
val MintDarkBackground = Color(0xFF171F1E)  // 带薄荷绿色调的深色背景
val MintDarkOnBackground = Color(0xFFE6E1E5)
val MintDarkSurface = Color(0xFF1A2221)  // 带薄荷绿色调的深色表面
val MintDarkOnSurface = Color(0xFFE6E1E5)
val MintDarkSurfaceVariant = Color(0xFF3E4746)  // 带薄荷绿色调
val MintDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val MintDarkOutline = Color(0xFF9E9E9E)
val MintDarkOutlineVariant = Color(0xFF616161)

// Amber Theme
// Light Mode
val AmberPrimary = Color(0xFFFFC107)
val AmberOnPrimary = Color(0xFF000000)
val AmberPrimaryContainer = Color(0xFFFFECB3)
val AmberOnPrimaryContainer = Color(0xFFFF6F00)
val AmberSecondary = Color(0xFFFFD54F)
val AmberOnSecondary = Color(0xFF000000)
val AmberSecondaryContainer = Color(0xFFFFF9C4)
val AmberOnSecondaryContainer = Color(0xFFFF8F00)
val AmberTertiary = Color(0xFFFFCA28)
val AmberOnTertiary = Color(0xFF000000)
val AmberTertiaryContainer = Color(0xFFFFF8E1)
val AmberOnTertiaryContainer = Color(0xFFFF6F00)
val AmberError = Color(0xFFB00020)
val AmberOnError = Color(0xFFFFFFFF)
val AmberErrorContainer = Color(0xFFFDEDED)
val AmberOnErrorContainer = Color(0xFF8C0009)
val AmberBackground = Color(0xFFFFFCF5)  // 带琥珀色调的背景
val AmberOnBackground = Color(0xFF1C1B1F)
val AmberSurface = Color(0xFFFFFEFA)  // 带琥珀色调的表面
val AmberOnSurface = Color(0xFF1C1B1F)
val AmberSurfaceVariant = Color(0xFFFFF8E1)
val AmberOnSurfaceVariant = Color(0xFF424242)
val AmberOutline = Color(0xFF757575)
val AmberOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val AmberDarkPrimary = Color(0xFFFFD54F)
val AmberDarkOnPrimary = Color(0xFF000000)
val AmberDarkPrimaryContainer = Color(0xFFFF8F00)
val AmberDarkOnPrimaryContainer = Color(0xFFFFECB3)
val AmberDarkSecondary = Color(0xFFFFE082)
val AmberDarkOnSecondary = Color(0xFF000000)
val AmberDarkSecondaryContainer = Color(0xFFFF8F00)
val AmberDarkOnSecondaryContainer = Color(0xFFFFF9C4)
val AmberDarkTertiary = Color(0xFFFFD54F)
val AmberDarkOnTertiary = Color(0xFF000000)
val AmberDarkTertiaryContainer = Color(0xFFFF6F00)
val AmberDarkOnTertiaryContainer = Color(0xFFFFF8E1)
val AmberDarkError = Color(0xFFCF6679)
val AmberDarkOnError = Color(0xFF000000)
val AmberDarkErrorContainer = Color(0xFFB00020)
val AmberDarkOnErrorContainer = Color(0xFFFDEDED)
val AmberDarkBackground = Color(0xFF1F1D17)  // 带琥珀色调的深色背景
val AmberDarkOnBackground = Color(0xFFE6E1E5)
val AmberDarkSurface = Color(0xFF23211A)  // 带琥珀色调的深色表面
val AmberDarkOnSurface = Color(0xFFE6E1E5)
val AmberDarkSurfaceVariant = Color(0xFF4A4740)  // 带琥珀色调
val AmberDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val AmberDarkOutline = Color(0xFF9E9E9E)
val AmberDarkOutlineVariant = Color(0xFF616161)

// Snow Theme
// Light Mode
val SnowPrimary = Color(0xFF90CAF9)
val SnowOnPrimary = Color(0xFF0D47A1)
val SnowPrimaryContainer = Color(0xFFE3F2FD)
val SnowOnPrimaryContainer = Color(0xFF1565C0)
val SnowSecondary = Color(0xFFBBDEFB)
val SnowOnSecondary = Color(0xFF0D47A1)
val SnowSecondaryContainer = Color(0xFFE1F5FE)
val SnowOnSecondaryContainer = Color(0xFF01579B)
val SnowTertiary = Color(0xFF81D4FA)
val SnowOnTertiary = Color(0xFF01579B)
val SnowTertiaryContainer = Color(0xFFB3E5FC)
val SnowOnTertiaryContainer = Color(0xFF0277BD)
val SnowError = Color(0xFFB00020)
val SnowOnError = Color(0xFFFFFFFF)
val SnowErrorContainer = Color(0xFFFDEDED)
val SnowOnErrorContainer = Color(0xFF8C0009)
val SnowBackground = Color(0xFFFFFBFE)
val SnowOnBackground = Color(0xFF1C1B1F)
val SnowSurface = Color(0xFFFFFBFE)
val SnowOnSurface = Color(0xFF1C1B1F)
val SnowSurfaceVariant = Color(0xFFE1F5FE)
val SnowOnSurfaceVariant = Color(0xFF424242)
val SnowOutline = Color(0xFF757575)
val SnowOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val SnowDarkPrimary = Color(0xFF64B5F6)
val SnowDarkOnPrimary = Color(0xFF0D47A1)
val SnowDarkPrimaryContainer = Color(0xFF1976D2)
val SnowDarkOnPrimaryContainer = Color(0xFFE3F2FD)
val SnowDarkSecondary = Color(0xFF81D4FA)
val SnowDarkOnSecondary = Color(0xFF01579B)
val SnowDarkSecondaryContainer = Color(0xFF0277BD)
val SnowDarkOnSecondaryContainer = Color(0xFFE1F5FE)
val SnowDarkTertiary = Color(0xFF4FC3F7)
val SnowDarkOnTertiary = Color(0xFF01579B)
val SnowDarkTertiaryContainer = Color(0xFF0277BD)
val SnowDarkOnTertiaryContainer = Color(0xFFB3E5FC)
val SnowDarkError = Color(0xFFCF6679)
val SnowDarkOnError = Color(0xFF000000)
val SnowDarkErrorContainer = Color(0xFFB00020)
val SnowDarkOnErrorContainer = Color(0xFFFDEDED)
val SnowDarkBackground = Color(0xFF1C1B1F)
val SnowDarkOnBackground = Color(0xFFE6E1E5)
val SnowDarkSurface = Color(0xFF1C1B1F)
val SnowDarkOnSurface = Color(0xFFE6E1E5)
val SnowDarkSurfaceVariant = Color(0xFF424242)
val SnowDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val SnowDarkOutline = Color(0xFF9E9E9E)
val SnowDarkOutlineVariant = Color(0xFF616161)

// Rain Theme
// Light Mode
val RainPrimary = Color(0xFF607D8B)
val RainOnPrimary = Color(0xFFFFFFFF)
val RainPrimaryContainer = Color(0xFFCFD8DC)
val RainOnPrimaryContainer = Color(0xFF263238)
val RainSecondary = Color(0xFF90A4AE)
val RainOnSecondary = Color(0xFFFFFFFF)
val RainSecondaryContainer = Color(0xFFECEFF1)
val RainOnSecondaryContainer = Color(0xFF37474F)
val RainTertiary = Color(0xFF78909C)
val RainOnTertiary = Color(0xFFFFFFFF)
val RainTertiaryContainer = Color(0xFFB0BEC5)
val RainOnTertiaryContainer = Color(0xFF263238)
val RainError = Color(0xFFB00020)
val RainOnError = Color(0xFFFFFFFF)
val RainErrorContainer = Color(0xFFFDEDED)
val RainOnErrorContainer = Color(0xFF8C0009)
val RainBackground = Color(0xFFFFFBFE)
val RainOnBackground = Color(0xFF1C1B1F)
val RainSurface = Color(0xFFFFFBFE)
val RainOnSurface = Color(0xFF1C1B1F)
val RainSurfaceVariant = Color(0xFFECEFF1)
val RainOnSurfaceVariant = Color(0xFF424242)
val RainOutline = Color(0xFF757575)
val RainOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val RainDarkPrimary = Color(0xFF90A4AE)
val RainDarkOnPrimary = Color(0xFF263238)
val RainDarkPrimaryContainer = Color(0xFF455A64)
val RainDarkOnPrimaryContainer = Color(0xFFCFD8DC)
val RainDarkSecondary = Color(0xFFB0BEC5)
val RainDarkOnSecondary = Color(0xFF263238)
val RainDarkSecondaryContainer = Color(0xFF546E7A)
val RainDarkOnSecondaryContainer = Color(0xFFECEFF1)
val RainDarkTertiary = Color(0xFF90A4AE)
val RainDarkOnTertiary = Color(0xFF263238)
val RainDarkTertiaryContainer = Color(0xFF455A64)
val RainDarkOnTertiaryContainer = Color(0xFFB0BEC5)
val RainDarkError = Color(0xFFCF6679)
val RainDarkOnError = Color(0xFF000000)
val RainDarkErrorContainer = Color(0xFFB00020)
val RainDarkOnErrorContainer = Color(0xFFFDEDED)
val RainDarkBackground = Color(0xFF1C1B1F)
val RainDarkOnBackground = Color(0xFFE6E1E5)
val RainDarkSurface = Color(0xFF1C1B1F)
val RainDarkOnSurface = Color(0xFFE6E1E5)
val RainDarkSurfaceVariant = Color(0xFF424242)
val RainDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val RainDarkOutline = Color(0xFF9E9E9E)
val RainDarkOutlineVariant = Color(0xFF616161)

// Maple Theme
// Light Mode
val MaplePrimary = Color(0xFFFF5722)
val MapleOnPrimary = Color(0xFFFFFFFF)
val MaplePrimaryContainer = Color(0xFFFFCCBC)
val MapleOnPrimaryContainer = Color(0xFFBF360C)
val MapleSecondary = Color(0xFFFF7043)
val MapleOnSecondary = Color(0xFFFFFFFF)
val MapleSecondaryContainer = Color(0xFFFFE0B2)
val MapleOnSecondaryContainer = Color(0xFFE64A19)
val MapleTertiary = Color(0xFFFF8A65)
val MapleOnTertiary = Color(0xFF000000)
val MapleTertiaryContainer = Color(0xFFFFD180)
val MapleOnTertiaryContainer = Color(0xFFD84315)
val MapleError = Color(0xFFB00020)
val MapleOnError = Color(0xFFFFFFFF)
val MapleErrorContainer = Color(0xFFFDEDED)
val MapleOnErrorContainer = Color(0xFF8C0009)
val MapleBackground = Color(0xFFFFFBFE)
val MapleOnBackground = Color(0xFF1C1B1F)
val MapleSurface = Color(0xFFFFFBFE)
val MapleOnSurface = Color(0xFF1C1B1F)
val MapleSurfaceVariant = Color(0xFFFFE0B2)
val MapleOnSurfaceVariant = Color(0xFF424242)
val MapleOutline = Color(0xFF757575)
val MapleOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val MapleDarkPrimary = Color(0xFFFF8A65)
val MapleDarkOnPrimary = Color(0xFFBF360C)
val MapleDarkPrimaryContainer = Color(0xFFE64A19)
val MapleDarkOnPrimaryContainer = Color(0xFFFFCCBC)
val MapleDarkSecondary = Color(0xFFFFAB91)
val MapleDarkOnSecondary = Color(0xFFBF360C)
val MapleDarkSecondaryContainer = Color(0xFFE64A19)
val MapleDarkOnSecondaryContainer = Color(0xFFFFE0B2)
val MapleDarkTertiary = Color(0xFFFFAB91)
val MapleDarkOnTertiary = Color(0xFFBF360C)
val MapleDarkTertiaryContainer = Color(0xFFD84315)
val MapleDarkOnTertiaryContainer = Color(0xFFFFD180)
val MapleDarkError = Color(0xFFCF6679)
val MapleDarkOnError = Color(0xFF000000)
val MapleDarkErrorContainer = Color(0xFFB00020)
val MapleDarkOnErrorContainer = Color(0xFFFDEDED)
val MapleDarkBackground = Color(0xFF1C1B1F)
val MapleDarkOnBackground = Color(0xFFE6E1E5)
val MapleDarkSurface = Color(0xFF1C1B1F)
val MapleDarkOnSurface = Color(0xFFE6E1E5)
val MapleDarkSurfaceVariant = Color(0xFF424242)
val MapleDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val MapleDarkOutline = Color(0xFF9E9E9E)
val MapleDarkOutlineVariant = Color(0xFF616161)

// Ocean Theme
// Light Mode
val OceanPrimary = Color(0xFF0288D1)
val OceanOnPrimary = Color(0xFFFFFFFF)
val OceanPrimaryContainer = Color(0xFFB3E5FC)
val OceanOnPrimaryContainer = Color(0xFF01579B)
val OceanSecondary = Color(0xFF03A9F4)
val OceanOnSecondary = Color(0xFFFFFFFF)
val OceanSecondaryContainer = Color(0xFF81D4FA)
val OceanOnSecondaryContainer = Color(0xFF0277BD)
val OceanTertiary = Color(0xFF29B6F6)
val OceanOnTertiary = Color(0xFFFFFFFF)
val OceanTertiaryContainer = Color(0xFFE1F5FE)
val OceanOnTertiaryContainer = Color(0xFF01579B)
val OceanError = Color(0xFFB00020)
val OceanOnError = Color(0xFFFFFFFF)
val OceanErrorContainer = Color(0xFFFDEDED)
val OceanOnErrorContainer = Color(0xFF8C0009)
val OceanBackground = Color(0xFFF5FBFF)  // 带海洋蓝色调的背景
val OceanOnBackground = Color(0xFF1C1B1F)
val OceanSurface = Color(0xFFF8FDFF)  // 带海洋蓝色调的表面
val OceanOnSurface = Color(0xFF1C1B1F)
val OceanSurfaceVariant = Color(0xFFE1F5FE)
val OceanOnSurfaceVariant = Color(0xFF424242)
val OceanOutline = Color(0xFF757575)
val OceanOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val OceanDarkPrimary = Color(0xFF4FC3F7)
val OceanDarkOnPrimary = Color(0xFF01579B)
val OceanDarkPrimaryContainer = Color(0xFF0277BD)
val OceanDarkOnPrimaryContainer = Color(0xFFB3E5FC)
val OceanDarkSecondary = Color(0xFF29B6F6)
val OceanDarkOnSecondary = Color(0xFF01579B)
val OceanDarkSecondaryContainer = Color(0xFF0277BD)
val OceanDarkOnSecondaryContainer = Color(0xFF81D4FA)
val OceanDarkTertiary = Color(0xFF4FC3F7)
val OceanDarkOnTertiary = Color(0xFF01579B)
val OceanDarkTertiaryContainer = Color(0xFF01579B)
val OceanDarkOnTertiaryContainer = Color(0xFFE1F5FE)
val OceanDarkError = Color(0xFFCF6679)
val OceanDarkOnError = Color(0xFF000000)
val OceanDarkErrorContainer = Color(0xFFB00020)
val OceanDarkOnErrorContainer = Color(0xFFFDEDED)
val OceanDarkBackground = Color(0xFF17191F)  // 带海洋蓝色调的深色背景
val OceanDarkOnBackground = Color(0xFFE6E1E5)
val OceanDarkSurface = Color(0xFF1A1D23)  // 带海洋蓝色调的深色表面
val OceanDarkOnSurface = Color(0xFFE6E1E5)
val OceanDarkSurfaceVariant = Color(0xFF424242)
val OceanDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val OceanDarkOutline = Color(0xFF9E9E9E)
val OceanDarkOutlineVariant = Color(0xFF616161)

// Sunset Theme
// Light Mode
val SunsetPrimary = Color(0xFFFF6F00)
val SunsetOnPrimary = Color(0xFFFFFFFF)
val SunsetPrimaryContainer = Color(0xFFFFE0B2)
val SunsetOnPrimaryContainer = Color(0xFFE65100)
val SunsetSecondary = Color(0xFFFF9800)
val SunsetOnSecondary = Color(0xFFFFFFFF)
val SunsetSecondaryContainer = Color(0xFFFFCC80)
val SunsetOnSecondaryContainer = Color(0xFFF57C00)
val SunsetTertiary = Color(0xFFFFB74D)
val SunsetOnTertiary = Color(0xFF000000)
val SunsetTertiaryContainer = Color(0xFFFFE0B2)
val SunsetOnTertiaryContainer = Color(0xFFEF6C00)
val SunsetError = Color(0xFFB00020)
val SunsetOnError = Color(0xFFFFFFFF)
val SunsetErrorContainer = Color(0xFFFDEDED)
val SunsetOnErrorContainer = Color(0xFF8C0009)
val SunsetBackground = Color(0xFFFFFBFE)
val SunsetOnBackground = Color(0xFF1C1B1F)
val SunsetSurface = Color(0xFFFFFBFE)
val SunsetOnSurface = Color(0xFF1C1B1F)
val SunsetSurfaceVariant = Color(0xFFFFE0B2)
val SunsetOnSurfaceVariant = Color(0xFF424242)
val SunsetOutline = Color(0xFF757575)
val SunsetOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val SunsetDarkPrimary = Color(0xFFFFB74D)
val SunsetDarkOnPrimary = Color(0xFFE65100)
val SunsetDarkPrimaryContainer = Color(0xFFF57C00)
val SunsetDarkOnPrimaryContainer = Color(0xFFFFE0B2)
val SunsetDarkSecondary = Color(0xFFFFCC80)
val SunsetDarkOnSecondary = Color(0xFFE65100)
val SunsetDarkSecondaryContainer = Color(0xFFF57C00)
val SunsetDarkOnSecondaryContainer = Color(0xFFFFCC80)
val SunsetDarkTertiary = Color(0xFFFFCC80)
val SunsetDarkOnTertiary = Color(0xFFE65100)
val SunsetDarkTertiaryContainer = Color(0xFFEF6C00)
val SunsetDarkOnTertiaryContainer = Color(0xFFFFE0B2)
val SunsetDarkError = Color(0xFFCF6679)
val SunsetDarkOnError = Color(0xFF000000)
val SunsetDarkErrorContainer = Color(0xFFB00020)
val SunsetDarkOnErrorContainer = Color(0xFFFDEDED)
val SunsetDarkBackground = Color(0xFF1C1B1F)
val SunsetDarkOnBackground = Color(0xFFE6E1E5)
val SunsetDarkSurface = Color(0xFF1C1B1F)
val SunsetDarkOnSurface = Color(0xFFE6E1E5)
val SunsetDarkSurfaceVariant = Color(0xFF424242)
val SunsetDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val SunsetDarkOutline = Color(0xFF9E9E9E)
val SunsetDarkOutlineVariant = Color(0xFF616161)

// Forest Theme
// Light Mode
val ForestPrimary = Color(0xFF388E3C)
val ForestOnPrimary = Color(0xFFFFFFFF)
val ForestPrimaryContainer = Color(0xFFC8E6C9)
val ForestOnPrimaryContainer = Color(0xFF1B5E20)
val ForestSecondary = Color(0xFF66BB6A)
val ForestOnSecondary = Color(0xFFFFFFFF)
val ForestSecondaryContainer = Color(0xFFE8F5E9)
val ForestOnSecondaryContainer = Color(0xFF2E7D32)
val ForestTertiary = Color(0xFF4CAF50)
val ForestOnTertiary = Color(0xFFFFFFFF)
val ForestTertiaryContainer = Color(0xFFA5D6A7)
val ForestOnTertiaryContainer = Color(0xFF1B5E20)
val ForestError = Color(0xFFB00020)
val ForestOnError = Color(0xFFFFFFFF)
val ForestErrorContainer = Color(0xFFFDEDED)
val ForestOnErrorContainer = Color(0xFF8C0009)
val ForestBackground = Color(0xFFFFFBFE)
val ForestOnBackground = Color(0xFF1C1B1F)
val ForestSurface = Color(0xFFFFFBFE)
val ForestOnSurface = Color(0xFF1C1B1F)
val ForestSurfaceVariant = Color(0xFFE8F5E9)
val ForestOnSurfaceVariant = Color(0xFF424242)
val ForestOutline = Color(0xFF757575)
val ForestOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val ForestDarkPrimary = Color(0xFF81C784)
val ForestDarkOnPrimary = Color(0xFF1B5E20)
val ForestDarkPrimaryContainer = Color(0xFF2E7D32)
val ForestDarkOnPrimaryContainer = Color(0xFFC8E6C9)
val ForestDarkSecondary = Color(0xFF81C784)
val ForestDarkOnSecondary = Color(0xFF1B5E20)
val ForestDarkSecondaryContainer = Color(0xFF388E3C)
val ForestDarkOnSecondaryContainer = Color(0xFFE8F5E9)
val ForestDarkTertiary = Color(0xFF66BB6A)
val ForestDarkOnTertiary = Color(0xFF1B5E20)
val ForestDarkTertiaryContainer = Color(0xFF2E7D32)
val ForestDarkOnTertiaryContainer = Color(0xFFA5D6A7)
val ForestDarkError = Color(0xFFCF6679)
val ForestDarkOnError = Color(0xFF000000)
val ForestDarkErrorContainer = Color(0xFFB00020)
val ForestDarkOnErrorContainer = Color(0xFFFDEDED)
val ForestDarkBackground = Color(0xFF1C1B1F)
val ForestDarkOnBackground = Color(0xFFE6E1E5)
val ForestDarkSurface = Color(0xFF1C1B1F)
val ForestDarkOnSurface = Color(0xFFE6E1E5)
val ForestDarkSurfaceVariant = Color(0xFF424242)
val ForestDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val ForestDarkOutline = Color(0xFF9E9E9E)
val ForestDarkOutlineVariant = Color(0xFF616161)

// Lavender Theme
// Light Mode
val LavenderPrimary = Color(0xFF9C27B0)
val LavenderOnPrimary = Color(0xFFFFFFFF)
val LavenderPrimaryContainer = Color(0xFFE1BEE7)
val LavenderOnPrimaryContainer = Color(0xFF4A148C)
val LavenderSecondary = Color(0xFFBA68C8)
val LavenderOnSecondary = Color(0xFFFFFFFF)
val LavenderSecondaryContainer = Color(0xFFF3E5F5)
val LavenderOnSecondaryContainer = Color(0xFF6A1B9A)
val LavenderTertiary = Color(0xFFAB47BC)
val LavenderOnTertiary = Color(0xFFFFFFFF)
val LavenderTertiaryContainer = Color(0xFFE1BEE7)
val LavenderOnTertiaryContainer = Color(0xFF4A148C)
val LavenderError = Color(0xFFB00020)
val LavenderOnError = Color(0xFFFFFFFF)
val LavenderErrorContainer = Color(0xFFFDEDED)
val LavenderOnErrorContainer = Color(0xFF8C0009)
val LavenderBackground = Color(0xFFFAF7FF)  // 带薰衣草紫色调的背景
val LavenderOnBackground = Color(0xFF1C1B1F)
val LavenderSurface = Color(0xFFFDFBFF)  // 带薰衣草紫色调的表面
val LavenderOnSurface = Color(0xFF1C1B1F)
val LavenderSurfaceVariant = Color(0xFFF3E5F5)
val LavenderOnSurfaceVariant = Color(0xFF424242)
val LavenderOutline = Color(0xFF757575)
val LavenderOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val LavenderDarkPrimary = Color(0xFFCE93D8)
val LavenderDarkOnPrimary = Color(0xFF4A148C)
val LavenderDarkPrimaryContainer = Color(0xFF7B1FA2)
val LavenderDarkOnPrimaryContainer = Color(0xFFE1BEE7)
val LavenderDarkSecondary = Color(0xFFBA68C8)
val LavenderDarkOnSecondary = Color(0xFF4A148C)
val LavenderDarkSecondaryContainer = Color(0xFF8E24AA)
val LavenderDarkOnSecondaryContainer = Color(0xFFF3E5F5)
val LavenderDarkTertiary = Color(0xFFCE93D8)
val LavenderDarkOnTertiary = Color(0xFF4A148C)
val LavenderDarkTertiaryContainer = Color(0xFF6A1B9A)
val LavenderDarkOnTertiaryContainer = Color(0xFFE1BEE7)
val LavenderDarkError = Color(0xFFCF6679)
val LavenderDarkOnError = Color(0xFF000000)
val LavenderDarkErrorContainer = Color(0xFFB00020)
val LavenderDarkOnErrorContainer = Color(0xFFFDEDED)
val LavenderDarkBackground = Color(0xFF1B1820)  // 带薰衣草紫色调的深色背景
val LavenderDarkOnBackground = Color(0xFFE6E1E5)
val LavenderDarkSurface = Color(0xFF1F1C24)  // 带薰衣草紫色调的深色表面
val LavenderDarkOnSurface = Color(0xFFE6E1E5)
val LavenderDarkSurfaceVariant = Color(0xFF49454F)
val LavenderDarkOnSurfaceVariant = Color(0xFFCAC4D0)
val LavenderDarkOutline = Color(0xFF938F99)
val LavenderDarkOutlineVariant = Color(0xFF49454F)

// Desert Theme
// Light Mode
val DesertPrimary = Color(0xFF8D6E63)
val DesertOnPrimary = Color(0xFFFFFFFF)
val DesertPrimaryContainer = Color(0xFFD7CCC8)
val DesertOnPrimaryContainer = Color(0xFF3E2723)
val DesertSecondary = Color(0xFFA1887F)
val DesertOnSecondary = Color(0xFFFFFFFF)
val DesertSecondaryContainer = Color(0xFFEFEBE9)
val DesertOnSecondaryContainer = Color(0xFF5D4037)
val DesertTertiary = Color(0xFFBCAAA4)
val DesertOnTertiary = Color(0xFF000000)
val DesertTertiaryContainer = Color(0xFFD7CCC8)
val DesertOnTertiaryContainer = Color(0xFF4E342E)
val DesertError = Color(0xFFB00020)
val DesertOnError = Color(0xFFFFFFFF)
val DesertErrorContainer = Color(0xFFFDEDED)
val DesertOnErrorContainer = Color(0xFF8C0009)
val DesertBackground = Color(0xFFFFFBFE)
val DesertOnBackground = Color(0xFF1C1B1F)
val DesertSurface = Color(0xFFFFFBFE)
val DesertOnSurface = Color(0xFF1C1B1F)
val DesertSurfaceVariant = Color(0xFFEFEBE9)
val DesertOnSurfaceVariant = Color(0xFF424242)
val DesertOutline = Color(0xFF757575)
val DesertOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val DesertDarkPrimary = Color(0xFFBCAAA4)
val DesertDarkOnPrimary = Color(0xFF3E2723)
val DesertDarkPrimaryContainer = Color(0xFF6D4C41)
val DesertDarkOnPrimaryContainer = Color(0xFFD7CCC8)
val DesertDarkSecondary = Color(0xFFBCAAA4)
val DesertDarkOnSecondary = Color(0xFF3E2723)
val DesertDarkSecondaryContainer = Color(0xFF5D4037)
val DesertDarkOnSecondaryContainer = Color(0xFFEFEBE9)
val DesertDarkTertiary = Color(0xFFD7CCC8)
val DesertDarkOnTertiary = Color(0xFF3E2723)
val DesertDarkTertiaryContainer = Color(0xFF4E342E)
val DesertDarkOnTertiaryContainer = Color(0xFFD7CCC8)
val DesertDarkError = Color(0xFFCF6679)
val DesertDarkOnError = Color(0xFF000000)
val DesertDarkErrorContainer = Color(0xFFB00020)
val DesertDarkOnErrorContainer = Color(0xFFFDEDED)
val DesertDarkBackground = Color(0xFF1C1B1F)
val DesertDarkOnBackground = Color(0xFFE6E1E5)
val DesertDarkSurface = Color(0xFF1C1B1F)
val DesertDarkOnSurface = Color(0xFFE6E1E5)
val DesertDarkSurfaceVariant = Color(0xFF424242)
val DesertDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val DesertDarkOutline = Color(0xFF9E9E9E)
val DesertDarkOutlineVariant = Color(0xFF616161)

// Aurora Theme
// Light Mode
val AuroraPrimary = Color(0xFF00BCD4)
val AuroraOnPrimary = Color(0xFFFFFFFF)
val AuroraPrimaryContainer = Color(0xFFB2EBF2)
val AuroraOnPrimaryContainer = Color(0xFF006064)
val AuroraSecondary = Color(0xFF26C6DA)
val AuroraOnSecondary = Color(0xFFFFFFFF)
val AuroraSecondaryContainer = Color(0xFFE0F7FA)
val AuroraOnSecondaryContainer = Color(0xFF00838F)
val AuroraTertiary = Color(0xFF18FFFF)
val AuroraOnTertiary = Color(0xFF000000)
val AuroraTertiaryContainer = Color(0xFF80DEEA)
val AuroraOnTertiaryContainer = Color(0xFF006064)
val AuroraError = Color(0xFFB00020)
val AuroraOnError = Color(0xFFFFFFFF)
val AuroraErrorContainer = Color(0xFFFDEDED)
val AuroraOnErrorContainer = Color(0xFF8C0009)
val AuroraBackground = Color(0xFFFFFBFE)
val AuroraOnBackground = Color(0xFF1C1B1F)
val AuroraSurface = Color(0xFFFFFBFE)
val AuroraOnSurface = Color(0xFF1C1B1F)
val AuroraSurfaceVariant = Color(0xFFE0F7FA)
val AuroraOnSurfaceVariant = Color(0xFF424242)
val AuroraOutline = Color(0xFF757575)
val AuroraOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode
val AuroraDarkPrimary = Color(0xFF4DD0E1)
val AuroraDarkOnPrimary = Color(0xFF006064)
val AuroraDarkPrimaryContainer = Color(0xFF0097A7)
val AuroraDarkOnPrimaryContainer = Color(0xFFB2EBF2)
val AuroraDarkSecondary = Color(0xFF26C6DA)
val AuroraDarkOnSecondary = Color(0xFF006064)
val AuroraDarkSecondaryContainer = Color(0xFF00838F)
val AuroraDarkOnSecondaryContainer = Color(0xFFE0F7FA)
val AuroraDarkTertiary = Color(0xFF18FFFF)
val AuroraDarkOnTertiary = Color(0xFF006064)
val AuroraDarkTertiaryContainer = Color(0xFF006064)
val AuroraDarkOnTertiaryContainer = Color(0xFF80DEEA)
val AuroraDarkError = Color(0xFFCF6679)
val AuroraDarkOnError = Color(0xFF000000)
val AuroraDarkErrorContainer = Color(0xFFB00020)
val AuroraDarkOnErrorContainer = Color(0xFFFDEDED)
val AuroraDarkBackground = Color(0xFF1C1B1F)
val AuroraDarkOnBackground = Color(0xFFE6E1E5)
val AuroraDarkSurface = Color(0xFF1C1B1F)
val AuroraDarkOnSurface = Color(0xFFE6E1E5)
val AuroraDarkSurfaceVariant = Color(0xFF424242)
val AuroraDarkOnSurfaceVariant = Color(0xFFBDBDBD)
val AuroraDarkOutline = Color(0xFF9E9E9E)
val AuroraDarkOutlineVariant = Color(0xFF616161)

// ============================================
// 💜 科技紫 (Tech Purple) - Material Design 3
// ============================================

// Light Mode - 5层紫色渐变，专业科技感
val TechPurplePrimary = Color(0xFF7B1FA2)
val TechPurpleOnPrimary = Color(0xFFFFFFFF)
val TechPurplePrimaryContainer = Color(0xFFF3E5F5)
val TechPurpleOnPrimaryContainer = Color(0xFF4A148C)
val TechPurpleSecondary = Color(0xFFBA68C8)
val TechPurpleOnSecondary = Color(0xFFFFFFFF)
val TechPurpleSecondaryContainer = Color(0xFFE1BEE7)
val TechPurpleOnSecondaryContainer = Color(0xFF6A1B9A)
val TechPurpleTertiary = Color(0xFF9C27B0)
val TechPurpleOnTertiary = Color(0xFFFFFFFF)
val TechPurpleTertiaryContainer = Color(0xFFCE93D8)
val TechPurpleOnTertiaryContainer = Color(0xFF4A148C)
val TechPurpleError = Color(0xFFB00020)
val TechPurpleOnError = Color(0xFFFFFFFF)
val TechPurpleErrorContainer = Color(0xFFFDEDED)
val TechPurpleOnErrorContainer = Color(0xFF8C0009)
val TechPurpleBackground = Color(0xFFFFFBFE)
val TechPurpleOnBackground = Color(0xFF1C1B1F)
val TechPurpleSurface = Color(0xFFFFFBFE)
val TechPurpleOnSurface = Color(0xFF1C1B1F)
val TechPurpleSurfaceVariant = Color(0xFFF3E5F5)
val TechPurpleOnSurfaceVariant = Color(0xFF49454F)
val TechPurpleOutline = Color(0xFF7A757F)
val TechPurpleOutlineVariant = Color(0xFFCAC4D0)

// Dark Mode - 反转亮度但保持色相
val TechPurplePrimaryDark = Color(0xFFCE93D8)
val TechPurpleOnPrimaryDark = Color(0xFF4A148C)
val TechPurplePrimaryContainerDark = Color(0xFF7B1FA2)
val TechPurpleOnPrimaryContainerDark = Color(0xFFF3E5F5)
val TechPurpleSecondaryDark = Color(0xFFBA68C8)
val TechPurpleOnSecondaryDark = Color(0xFF4A148C)
val TechPurpleSecondaryContainerDark = Color(0xFF8E24AA)
val TechPurpleOnSecondaryContainerDark = Color(0xFFE1BEE7)
val TechPurpleTertiaryDark = Color(0xFFE1BEE7)
val TechPurpleOnTertiaryDark = Color(0xFF4A148C)
val TechPurpleTertiaryContainerDark = Color(0xFF9C27B0)
val TechPurpleOnTertiaryContainerDark = Color(0xFFCE93D8)
val TechPurpleErrorDark = Color(0xFFCF6679)
val TechPurpleOnErrorDark = Color(0xFF000000)
val TechPurpleErrorContainerDark = Color(0xFFB00020)
val TechPurpleOnErrorContainerDark = Color(0xFFFDEDED)
val TechPurpleBackgroundDark = Color(0xFF1C1B1F)
val TechPurpleOnBackgroundDark = Color(0xFFE6E1E5)
val TechPurpleSurfaceDark = Color(0xFF1C1B1F)
val TechPurpleOnSurfaceDark = Color(0xFFE6E1E5)
val TechPurpleSurfaceVariantDark = Color(0xFF49454F)
val TechPurpleOnSurfaceVariantDark = Color(0xFFCAC4D0)
val TechPurpleOutlineDark = Color(0xFF938F99)
val TechPurpleOutlineVariantDark = Color(0xFF49454F)

// ============================================
// 🐍 黑曼巴 (Black Mamba - Lakers) - Material Design 3
// ============================================

// Light Mode - 湖人配色：金色 + 紫色 + 黑色
val BlackMambaPrimary = Color(0xFFFDB927)  // Lakers Gold
val BlackMambaOnPrimary = Color(0xFF000000)
val BlackMambaPrimaryContainer = Color(0xFFFFF9E6)
val BlackMambaOnPrimaryContainer = Color(0xFF8B6914)
val BlackMambaSecondary = Color(0xFF552583)  // Lakers Purple
val BlackMambaOnSecondary = Color(0xFFFFFFFF)
val BlackMambaSecondaryContainer = Color(0xFFE8D5F5)
val BlackMambaOnSecondaryContainer = Color(0xFF2D1347)
val BlackMambaTertiary = Color(0xFF000000)  // Black Mamba
val BlackMambaOnTertiary = Color(0xFFFFFFFF)
val BlackMambaTertiaryContainer = Color(0xFF424242)
val BlackMambaOnTertiaryContainer = Color(0xFFE0E0E0)
val BlackMambaError = Color(0xFFB00020)
val BlackMambaOnError = Color(0xFFFFFFFF)
val BlackMambaErrorContainer = Color(0xFFFDEDED)
val BlackMambaOnErrorContainer = Color(0xFF8C0009)
val BlackMambaBackground = Color(0xFFFFFBFE)
val BlackMambaOnBackground = Color(0xFF1C1B1F)
val BlackMambaSurface = Color(0xFFFFFBFE)
val BlackMambaOnSurface = Color(0xFF1C1B1F)
val BlackMambaSurfaceVariant = Color(0xFFFFF9E6)
val BlackMambaOnSurfaceVariant = Color(0xFF424242)
val BlackMambaOutline = Color(0xFF757575)
val BlackMambaOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode - 深色背景突出金色和紫色
val BlackMambaPrimaryDark = Color(0xFFFDB927)
val BlackMambaOnPrimaryDark = Color(0xFF000000)
val BlackMambaPrimaryContainerDark = Color(0xFF8B6914)
val BlackMambaOnPrimaryContainerDark = Color(0xFFFFF9E6)
val BlackMambaSecondaryDark = Color(0xFF9D7FC4)
val BlackMambaOnSecondaryDark = Color(0xFF2D1347)
val BlackMambaSecondaryContainerDark = Color(0xFF552583)
val BlackMambaOnSecondaryContainerDark = Color(0xFFE8D5F5)
val BlackMambaTertiaryDark = Color(0xFF616161)
val BlackMambaOnTertiaryDark = Color(0xFFFFFFFF)
val BlackMambaTertiaryContainerDark = Color(0xFF212121)
val BlackMambaOnTertiaryContainerDark = Color(0xFFE0E0E0)
val BlackMambaErrorDark = Color(0xFFCF6679)
val BlackMambaOnErrorDark = Color(0xFF000000)
val BlackMambaErrorContainerDark = Color(0xFFB00020)
val BlackMambaOnErrorContainerDark = Color(0xFFFDEDED)
val BlackMambaBackgroundDark = Color(0xFF1C1B1F)
val BlackMambaOnBackgroundDark = Color(0xFFE6E1E5)
val BlackMambaSurfaceDark = Color(0xFF1C1B1F)
val BlackMambaOnSurfaceDark = Color(0xFFE6E1E5)
val BlackMambaSurfaceVariantDark = Color(0xFF2C2C2C)
val BlackMambaOnSurfaceVariantDark = Color(0xFFBDBDBD)
val BlackMambaOutlineDark = Color(0xFF9E9E9E)
val BlackMambaOutlineVariantDark = Color(0xFF616161)

// ============================================
// 🕴️ 小黑紫 (Grey Style) - Material Design 3
// ============================================

// Light Mode - 紫色与灰色的优雅组合（60-30-10配色比例）
val GreyStylePrimary = Color(0xFF9575CD)
val GreyStyleOnPrimary = Color(0xFFFFFFFF)
val GreyStylePrimaryContainer = Color(0xFFEDE7F6)
val GreyStyleOnPrimaryContainer = Color(0xFF512DA8)
val GreyStyleSecondary = Color(0xFF78909C)
val GreyStyleOnSecondary = Color(0xFFFFFFFF)
val GreyStyleSecondaryContainer = Color(0xFFECEFF1)
val GreyStyleOnSecondaryContainer = Color(0xFF455A64)
val GreyStyleTertiary = Color(0xFFB39DDB)
val GreyStyleOnTertiary = Color(0xFF000000)
val GreyStyleTertiaryContainer = Color(0xFFF3E5F5)
val GreyStyleOnTertiaryContainer = Color(0xFF7B1FA2)
val GreyStyleError = Color(0xFFB00020)
val GreyStyleOnError = Color(0xFFFFFFFF)
val GreyStyleErrorContainer = Color(0xFFFDEDED)
val GreyStyleOnErrorContainer = Color(0xFF8C0009)
val GreyStyleBackground = Color(0xFFFFFBFE)
val GreyStyleOnBackground = Color(0xFF1C1B1F)
val GreyStyleSurface = Color(0xFFFFFBFE)
val GreyStyleOnSurface = Color(0xFF1C1B1F)
val GreyStyleSurfaceVariant = Color(0xFFECEFF1)
val GreyStyleOnSurfaceVariant = Color(0xFF424242)
val GreyStyleOutline = Color(0xFF757575)
val GreyStyleOutlineVariant = Color(0xFFBDBDBD)

// Dark Mode - 保持紫灰平衡
val GreyStylePrimaryDark = Color(0xFFB39DDB)
val GreyStyleOnPrimaryDark = Color(0xFF512DA8)
val GreyStylePrimaryContainerDark = Color(0xFF7E57C2)
val GreyStyleOnPrimaryContainerDark = Color(0xFFEDE7F6)
val GreyStyleSecondaryDark = Color(0xFF90A4AE)
val GreyStyleOnSecondaryDark = Color(0xFF263238)
val GreyStyleSecondaryContainerDark = Color(0xFF607D8B)
val GreyStyleOnSecondaryContainerDark = Color(0xFFECEFF1)
val GreyStyleTertiaryDark = Color(0xFFCE93D8)
val GreyStyleOnTertiaryDark = Color(0xFF4A148C)
val GreyStyleTertiaryContainerDark = Color(0xFF9C27B0)
val GreyStyleOnTertiaryContainerDark = Color(0xFFF3E5F5)
val GreyStyleErrorDark = Color(0xFFCF6679)
val GreyStyleOnErrorDark = Color(0xFF000000)
val GreyStyleErrorContainerDark = Color(0xFFB00020)
val GreyStyleOnErrorContainerDark = Color(0xFFFDEDED)
val GreyStyleBackgroundDark = Color(0xFF1C1B1F)
val GreyStyleOnBackgroundDark = Color(0xFFE6E1E5)
val GreyStyleSurfaceDark = Color(0xFF1C1B1F)
val GreyStyleOnSurfaceDark = Color(0xFFE6E1E5)
val GreyStyleSurfaceVariantDark = Color(0xFF424242)
val GreyStyleOnSurfaceVariantDark = Color(0xFFBDBDBD)
val GreyStyleOutlineDark = Color(0xFF9E9E9E)
val GreyStyleOutlineVariantDark = Color(0xFF616161)
